### ISSUE TITLE
Compatibility issue with Axon

### ISSUE THREAD

**Issue by holy-elbow** [Mysteryexe/Reo#1]
When Reo is enabled Axon/grupi does not appear making notifications invisible. No combination of settings in either tweak fixes the issue. iPhone 13 ios 15.5b4

**Comment by Mysteryexe** [comment]
Working on it mate!

**Comment by Mysteryexe** [comment]
fixed problem with axon/dodo/veza/etc on 2.2.0

**Comment by holy-elbow** [comment]
That was fast! Thank you! Love the tweak
